(window.webpackJsonp=window.webpackJsonp||[]).push([[140],{534:function(t,a,r){"use strict";r.r(a);var e=r(2),n=Object(e.a)({},(function(){var t=this,a=t._self._c;return a("ContentSlotsDistributor",{attrs:{"slot-key":t.$parent.slotKey}},[a("h1",{attrs:{id:"exception"}},[a("a",{staticClass:"header-anchor",attrs:{href:"#exception"}},[t._v("#")]),t._v(" Exception")]),t._v(" "),a("p",[t._v("Try-catch自定义异常类使用方法：")]),t._v(" "),a("p",[a("img",{attrs:{src:"https://markdown-1301334775.cos.eu-frankfurt.myqcloud.com/image-20230426222350755.png",alt:"image-20230426222350755"}})]),t._v(" "),a("p",[t._v("一般使用System.err.println();来输出错误，因为System.out可能会被重定向。")]),t._v(" "),a("p",[t._v("Exception继承了Throwable")]),t._v(" "),a("p",[t._v("默认的方法：e.printStackTrace();将会提示方法调用处以及异常抛出处。")]),t._v(" "),a("p",[t._v("重新抛出异常会把异常抛给上一级异常处理程序")]),t._v(" "),a("p",[a("img",{attrs:{src:"https://markdown-1301334775.cos.eu-frankfurt.myqcloud.com/image-20230426222407885.png",alt:"image-20230426222407885"}})]),t._v(" "),a("p",[a("img",{attrs:{src:"https://markdown-1301334775.cos.eu-frankfurt.myqcloud.com/image-20230426222418216.png",alt:"image-20230426222418216"}})]),t._v(" "),a("p",[a("img",{attrs:{src:"https://markdown-1301334775.cos.eu-frankfurt.myqcloud.com/image-20230426222428991.png",alt:"image-20230426222428991"}})]),t._v(" "),a("p",[t._v("RuntimeException会自动捕获，finally不管是否抛出错误都执行")])])}),[],!1,null,null,null);a.default=n.exports}}]);